// Crucible Lattice — mock demo data.
// Three hand-crafted examples + a generic fallback for free-form input.

const EXAMPLES = {
  hypersonic: {
    id: 'hypersonic',
    label: 'Hypersonic Coating Precursor',
    subtitle: 'UHTC precursor — defense / aerospace',
    tag: 'DEFENSE',
    tagColor: 'amber',
    input: {
      smiles: 'CO[Si](OC)(OC)c1ccccc1',
      name: 'PTMS-X7',
      useCase: 'Oxidation-resistant thermal barrier coating for hypersonic vehicle leading edges. Target service temp 1800–2000°C, ablation rate <0.05 mm/min in Mach 7 airstream.',
      quantity: '500 kg / month',
      timeline: '18 months to IOC',
    },
    identity: {
      name: 'PTMS-X7 Precursor',
      formula: 'C₉H₁₄O₃Si',
      molecularWeight: '198.29 g/mol',
      classification: 'Organosilicon (alkoxysilane) — ceramic precursor',
      state: 'Clear liquid @ 25 °C',
    },
    regulatory: [
      { label: 'REACH (EU)', status: 'pass', note: 'Registered; no SVHC' },
      { label: 'TSCA (US)', status: 'pass', note: 'Listed on inventory' },
      { label: 'ITAR / EAR', status: 'flag', note: 'Defense end-use detected — US-domestic supply chain enforced, no foreign partners surfaced' },
      { label: 'DEA Schedule', status: 'na', note: 'Not a controlled substance' },
      { label: 'DoD Qualification', status: 'pass', note: 'Compatible with MIL-STD-883 test methods' },
    ],
    hazard: {
      summary: 'Moisture-sensitive, flammable liquid (UN 1993, Class 3, PG III). Requires dry N₂ handling.',
      flags: ['Moisture-sensitive', 'Flammable (Class 3)', 'Mild skin/eye irritant'],
    },
    purity: [
      { scale: 'Bench (100 g)', target: '≥99.0 %',  method: 'GC-FID' },
      { scale: 'Pilot (10 kg)', target: '≥99.5 %',  method: 'GC-MS + ²⁹Si NMR' },
      { scale: 'Commercial (500 kg/mo)', target: '≥99.8 %', method: 'Full COA w/ ICP-MS trace metals <5 ppm' },
    ],
    optimization: null,
    scenarios: [
      {
        name: 'Lowest Cost',
        icon: '$',
        cost: '$1.82M / yr',
        costPerKg: '$303',
        leadTime: '14 weeks',
        partnerCount: 4,
        highlight: 'Direct feedstock from domestic silicon producer',
        radar: { cost: 92, speed: 68, risk: 55, sustainability: 48, compliance: 95, scalability: 72 },
        partners: ['Orogen Silicates (feedstock)', 'Nuada Specialty Chem (synthesis)', 'Basilisk Fine Chem (purification)', 'Arcline Logistics (ITAR-cleared transport)'],
      },
      {
        name: 'Fastest',
        icon: '⚡',
        cost: '$2.41M / yr',
        costPerKg: '$402',
        leadTime: '6 weeks',
        partnerCount: 3,
        highlight: 'Reserved capacity at pre-qualified integrated facility',
        radar: { cost: 62, speed: 95, risk: 70, sustainability: 40, compliance: 95, scalability: 85 },
        partners: ['Helix Organics (integrated synth + purification)', 'Meridian Silanes (backup feedstock)', 'Arcline Logistics'],
      },
      {
        name: 'Fewest Partners',
        icon: '◈',
        cost: '$2.18M / yr',
        costPerKg: '$363',
        leadTime: '10 weeks',
        partnerCount: 2,
        highlight: 'Single-point-of-contact, vertically integrated',
        radar: { cost: 74, speed: 80, risk: 60, sustainability: 52, compliance: 95, scalability: 78 },
        partners: ['Helix Organics (full-stack)', 'Arcline Logistics'],
      },
      {
        name: 'Lowest Risk',
        icon: '◉',
        cost: '$2.63M / yr',
        costPerKg: '$438',
        leadTime: '12 weeks',
        partnerCount: 5,
        highlight: 'Dual-source every critical node, 2× ITAR-cleared facilities',
        radar: { cost: 52, speed: 72, risk: 95, sustainability: 55, compliance: 98, scalability: 88 },
        partners: ['Orogen Silicates (primary)', 'Meridian Silanes (secondary)', 'Nuada Specialty Chem', 'Basilisk Fine Chem (redundant purification)', 'Arcline Logistics'],
      },
    ],
    map: {
      caption: '11 qualified partners screened · 4 pass ITAR gate · all US-domestic',
      nodes: [
        { x: 22, y: 58, name: 'Orogen Silicates',   role: 'Feedstock',   active: true,  tier: 1 },
        { x: 35, y: 42, name: 'Meridian Silanes',   role: 'Feedstock',   active: true,  tier: 2 },
        { x: 50, y: 55, name: 'Nuada Specialty',    role: 'Synthesis',   active: true,  tier: 1 },
        { x: 48, y: 32, name: 'Helix Organics',     role: 'Integrated',  active: true,  tier: 1 },
        { x: 68, y: 48, name: 'Basilisk Fine Chem', role: 'Purification',active: true,  tier: 1 },
        { x: 78, y: 62, name: 'Arcline Logistics',  role: 'Logistics',   active: true,  tier: 1 },
        { x: 14, y: 30, name: 'Tengri Hydromet',    role: 'Filtered',    active: false, tier: 3 },
        { x: 85, y: 28, name: 'Quanta Catalysts',   role: 'Filtered',    active: false, tier: 3 },
        { x: 60, y: 78, name: 'Mercia Bio',         role: 'Filtered',    active: false, tier: 3 },
      ],
    },
  },

  drug: {
    id: 'drug',
    label: 'Small-Molecule Drug Intermediate',
    subtitle: 'Phase-I Nav1.8 inhibitor candidate',
    tag: 'PHARMA',
    tagColor: 'cyan',
    input: {
      smiles: 'O=C(Nc1ccc(F)cc1)c1ccc2[nH]ncc2c1',
      name: 'CL-2847',
      useCase: 'Selective Nav1.8 sodium-channel inhibitor for non-opioid chronic pain. Entering Phase I trials; needs clinical-grade API.',
      quantity: '25 kg total for Ph I + Ph II',
      timeline: '9 months to GMP release',
    },
    identity: {
      name: 'CL-2847 (indazole-6-carboxamide)',
      formula: 'C₁₄H₁₀FN₃O',
      molecularWeight: '255.25 g/mol',
      classification: 'Small-molecule API — indazole carboxamide',
      state: 'Off-white crystalline solid',
    },
    regulatory: [
      { label: 'ICH Q7 (cGMP API)', status: 'pass', note: 'Route compatible with ICH Q7; QbD documentation required' },
      { label: 'FDA DMF', status: 'flag', note: 'Type II DMF filing needed prior to Ph II — auto-queued' },
      { label: 'REACH (EU)', status: 'pass', note: 'Under clinical-use exemption' },
      { label: 'DEA Schedule', status: 'na', note: 'Non-scheduled' },
      { label: 'Genotoxic impurities', status: 'pass', note: 'No ICH M7 Class 1–2 alerts in route' },
    ],
    hazard: {
      summary: 'Low acute toxicity. Standard OEL-3 handling (1–10 μg/m³). No special shipping class.',
      flags: ['OEL-3 containment', 'Photosensitive — amber glass'],
    },
    purity: [
      { scale: 'Bench (100 g)', target: '≥98.0 %',  method: 'HPLC-UV' },
      { scale: 'Pilot (2 kg)',  target: '≥99.5 %',  method: 'HPLC-UV + ¹H NMR + residual solvents GC' },
      { scale: 'Clinical (25 kg)', target: '≥99.9 %, single impurity ≤0.10 %', method: 'Full ICH Q6A COA, genotox screen, polymorph ID' },
    ],
    optimization: {
      severity: 'high',
      title: 'Optimization Potential Detected',
      finding: 'Step-3 fluorination uses Selectfluor at 0 °C (34 % yield, REACH-restricted solvent DMF).',
      suggestion: 'Replace 4-fluoroaniline coupling partner with 4-chloro analog → swap to late-stage Pd-catalyzed C–F via Balz-Schiemann variant.',
      impact: [
        { metric: 'Overall yield',   from: '34 %',  to: '71 %',  delta: '+109 %' },
        { metric: 'Cost / kg API',   from: '$4,820', to: '$2,110', delta: '−56 %' },
        { metric: 'E-factor',        from: '148',  to: '62',   delta: '−58 %' },
        { metric: 'REACH flags',     from: '2',    to: '0',    delta: 'cleared' },
      ],
      cta: 'Engage Crucible chemistry team to co-develop revised route (NDA + JDA template available).',
    },
    scenarios: [
      {
        name: 'Lowest Cost',
        icon: '$',
        cost: '$1.41M total program',
        costPerKg: '$56,400',
        leadTime: '22 weeks',
        partnerCount: 4,
        highlight: 'India-based cGMP CDMO with FDA history',
        radar: { cost: 94, speed: 60, risk: 58, sustainability: 52, compliance: 78, scalability: 80 },
        partners: ['Sarna Pharma (API synthesis, India)', 'Veridia Intermediates (key starting material)', 'Aurora QC Labs (release testing, US)', 'CryoLink Cold Chain'],
      },
      {
        name: 'Fastest',
        icon: '⚡',
        cost: '$2.08M total program',
        costPerKg: '$83,200',
        leadTime: '11 weeks',
        partnerCount: 3,
        highlight: 'Reserved EU cGMP suite, no tech-transfer delay',
        radar: { cost: 68, speed: 96, risk: 72, sustainability: 60, compliance: 94, scalability: 75 },
        partners: ['Helvetia GMP (integrated API, Switzerland)', 'Aurora QC Labs', 'CryoLink Cold Chain'],
      },
      {
        name: 'Fewest Partners',
        icon: '◈',
        cost: '$1.92M total program',
        costPerKg: '$76,800',
        leadTime: '16 weeks',
        partnerCount: 2,
        highlight: 'One-stop CDMO handles synth, QC, release',
        radar: { cost: 74, speed: 82, risk: 68, sustainability: 58, compliance: 92, scalability: 82 },
        partners: ['Helvetia GMP (full-stack)', 'CryoLink Cold Chain'],
      },
      {
        name: 'Greenest',
        icon: '◊',
        cost: '$1.77M total program',
        costPerKg: '$70,800',
        leadTime: '18 weeks',
        partnerCount: 4,
        highlight: 'Biocatalytic step-2 + solvent recovery loop',
        radar: { cost: 78, speed: 72, risk: 65, sustainability: 94, compliance: 90, scalability: 74 },
        partners: ['Mycelia BioCatalysis (enzymatic step)', 'Helvetia GMP (downstream)', 'Aurora QC Labs', 'CryoLink Cold Chain'],
      },
    ],
    map: {
      caption: '18 cGMP-qualified partners screened · 6 match API class · 4 pass genotox gate',
      nodes: [
        { x: 20, y: 48, name: 'Sarna Pharma',    role: 'API Synth',    active: true,  tier: 1 },
        { x: 35, y: 62, name: 'Veridia Inter.',  role: 'Intermediate', active: true,  tier: 1 },
        { x: 52, y: 38, name: 'Helvetia GMP',    role: 'Integrated',   active: true,  tier: 1 },
        { x: 48, y: 68, name: 'Mycelia BioCat',  role: 'Biocatalysis', active: true,  tier: 2 },
        { x: 70, y: 50, name: 'Aurora QC',       role: 'QC / Release', active: true,  tier: 1 },
        { x: 82, y: 36, name: 'CryoLink',        role: 'Cold Chain',   active: true,  tier: 1 },
        { x: 15, y: 75, name: 'Regent Actives',  role: 'Filtered',     active: false, tier: 3 },
        { x: 88, y: 70, name: 'Polaris Pharma',  role: 'Filtered',     active: false, tier: 3 },
        { x: 62, y: 20, name: 'Kestrel Labs',    role: 'Filtered',     active: false, tier: 3 },
      ],
    },
  },

  lubricant: {
    id: 'lubricant',
    label: 'High-Performance Lubricant Ester',
    subtitle: 'Industrial synthetic base stock',
    tag: 'INDUSTRIAL',
    tagColor: 'green',
    input: {
      smiles: 'CCCCC(CC)C(=O)OCC(COC(=O)C(CC)CCCC)(COC(=O)C(CC)CCCC)COC(=O)C(CC)CCCC',
      name: 'PE-4EH (Pentaerythritol tetra-2-ethylhexanoate)',
      useCase: 'Synthetic base stock for wind-turbine gearbox lubricant. Target VI >140, pour point <−45 °C, biodegradable per OECD 301B.',
      quantity: '12,000 metric tons / year',
      timeline: '24 months to full production',
    },
    identity: {
      name: 'PE-4EH Synthetic Ester',
      formula: 'C₃₇H₆₈O₈',
      molecularWeight: '640.93 g/mol',
      classification: 'Neopentyl polyol ester (Group V base stock)',
      state: 'Pale yellow viscous liquid',
    },
    regulatory: [
      { label: 'REACH (EU)', status: 'pass', note: 'Full registration, tonnage band 1000–10000 t/y' },
      { label: 'TSCA (US)', status: 'pass', note: 'Listed; low-concern profile' },
      { label: 'OECD 301B', status: 'pass', note: 'Readily biodegradable (68 % @ 28d)' },
      { label: 'EU Ecolabel', status: 'pass', note: 'Meets criteria for wind-turbine lubes' },
      { label: 'Food-grade (NSF H1)', status: 'na', note: 'Not required for this use case' },
    ],
    hazard: {
      summary: 'Low hazard. Not classified as dangerous goods. Standard drum / IBC shipping.',
      flags: ['Non-hazardous', 'Readily biodegradable'],
    },
    purity: [
      { scale: 'Pilot (1 t)', target: 'Acid # ≤0.05 mg KOH/g', method: 'Titration + GC' },
      { scale: 'Commercial (1000 t/mo)', target: 'Acid # ≤0.03, water ≤50 ppm', method: 'Inline NIR + batch COA' },
      { scale: 'Full scale (12 kt/y)', target: 'Spec-locked to OEM approval', method: 'Real-time QC, ISO 4406 particle count' },
    ],
    optimization: {
      severity: 'medium',
      title: 'Feedstock Substitution Opportunity',
      finding: 'The conventional industrial route for PE-4EH relies on petroleum-derived 2-ethylhexanol as the acid precursor — a structural default inherited from incumbent manufacturing.',
      suggestion: 'A drop-in bio-2-EH from fermented sugar feedstock is now commercially available at ~1.08× cost and qualifies under the same OEM specs.',
      impact: [
        { metric: 'Bio-carbon content', from: '0 %',   to: '64 %',  delta: '+64 pts' },
        { metric: 'Cradle-to-gate CO₂', from: '3.2 kg/kg', to: '1.1 kg/kg', delta: '−66 %' },
        { metric: 'Unit cost',          from: '$4.40/kg', to: '$4.75/kg', delta: '+8 %' },
        { metric: 'EU Ecolabel tier',   from: 'Standard', to: 'Premium', delta: 'upgraded' },
      ],
      cta: 'Model the bio-feedstock scenario side-by-side with incumbent route.',
    },
    scenarios: [
      {
        name: 'Lowest Cost',
        icon: '$',
        cost: '$52.8M / yr',
        costPerKg: '$4.40',
        leadTime: '16 weeks (first shipment)',
        partnerCount: 5,
        highlight: 'Petrochemical feedstock, Gulf Coast integrated cluster',
        radar: { cost: 95, speed: 80, risk: 62, sustainability: 40, compliance: 85, scalability: 96 },
        partners: ['Gulfstar Oleochem (feedstock)', 'Meridian Esters (synthesis)', 'Catalyst Refiners', 'Orogen Packaging', 'Continental Bulk Logistics'],
      },
      {
        name: 'Fastest',
        icon: '⚡',
        cost: '$58.2M / yr',
        costPerKg: '$4.85',
        leadTime: '10 weeks',
        partnerCount: 3,
        highlight: 'Repurposes idle EU ester capacity',
        radar: { cost: 78, speed: 95, risk: 66, sustainability: 58, compliance: 90, scalability: 84 },
        partners: ['Helvetia Esters (integrated)', 'Meridian Esters (backup)', 'Continental Bulk Logistics'],
      },
      {
        name: 'Greenest',
        icon: '◊',
        cost: '$57.0M / yr',
        costPerKg: '$4.75',
        leadTime: '20 weeks',
        partnerCount: 4,
        highlight: 'Bio-2-EH feedstock, solar-powered esterification',
        radar: { cost: 82, speed: 72, risk: 60, sustainability: 96, compliance: 94, scalability: 82 },
        partners: ['Mycelia Bio-Alcohols (feedstock)', 'Verdant Green Chem (esterification)', 'Orogen Packaging (recycled HDPE)', 'Continental Bulk Logistics'],
      },
      {
        name: 'Lowest Risk',
        icon: '◉',
        cost: '$55.4M / yr',
        costPerKg: '$4.62',
        leadTime: '14 weeks',
        partnerCount: 6,
        highlight: 'Dual-continent sourcing, no single-point-of-failure',
        radar: { cost: 86, speed: 78, risk: 94, sustainability: 62, compliance: 92, scalability: 92 },
        partners: ['Gulfstar Oleochem', 'Helvetia Esters', 'Meridian Esters', 'Catalyst Refiners', 'Orogen Packaging', 'Continental Bulk Logistics'],
      },
    ],
    map: {
      caption: '34 partners screened · 9 match polyol-ester capability · 6 in final mix',
      nodes: [
        { x: 15, y: 55, name: 'Gulfstar Oleochem', role: 'Feedstock',  active: true,  tier: 1 },
        { x: 28, y: 38, name: 'Mycelia Bio-Alc',   role: 'Bio-feed',   active: true,  tier: 2 },
        { x: 45, y: 60, name: 'Meridian Esters',   role: 'Synthesis',  active: true,  tier: 1 },
        { x: 52, y: 32, name: 'Verdant Green',     role: 'Green synth',active: true,  tier: 2 },
        { x: 64, y: 48, name: 'Helvetia Esters',   role: 'Integrated', active: true,  tier: 1 },
        { x: 75, y: 68, name: 'Catalyst Refiners', role: 'Polish',     active: true,  tier: 1 },
        { x: 82, y: 36, name: 'Orogen Packaging',  role: 'Packaging',  active: true,  tier: 1 },
        { x: 90, y: 55, name: 'Continental Bulk',  role: 'Logistics',  active: true,  tier: 1 },
        { x: 10, y: 78, name: 'Regent Oleo',       role: 'Filtered',   active: false, tier: 3 },
        { x: 35, y: 82, name: 'Polaris Esters',    role: 'Filtered',   active: false, tier: 3 },
      ],
    },
  },
};

// Fallback for free-typed molecules. Generic but plausible.
const GENERIC = {
  id: 'generic',
  label: 'Custom Submission',
  subtitle: 'Partner network analysis',
  tag: 'UNCLASSIFIED',
  tagColor: 'slate',
  identity: {
    name: 'Custom Compound',
    formula: '—',
    molecularWeight: '—',
    classification: 'Pending deeper classification',
    state: 'To be characterized',
  },
  regulatory: [
    { label: 'REACH (EU)', status: 'pass', note: 'No structural alerts; pre-registration recommended' },
    { label: 'TSCA (US)', status: 'flag', note: 'Pre-manufacture notice (PMN) may be required — auto-flagged for review' },
    { label: 'DEA Schedule', status: 'pass', note: 'No scheduled-substance matches' },
    { label: 'GHS Classification', status: 'pass', note: 'No high-severity hazard alerts detected' },
    { label: 'Export Controls', status: 'pass', note: 'No ECCN matches in preliminary scan' },
  ],
  hazard: {
    summary: 'Preliminary screen — no high-severity alerts. Deeper characterization recommended before scale-up.',
    flags: ['Preliminary assessment', 'Characterization pending'],
  },
  purity: [
    { scale: 'Bench',      target: '≥98.0 %', method: 'HPLC or GC (method TBD)' },
    { scale: 'Pilot',      target: '≥99.0 %', method: 'Orthogonal methods + NMR' },
    { scale: 'Commercial', target: '≥99.5 %', method: 'Full COA, method validation' },
  ],
  optimization: {
    severity: 'medium',
    title: 'Route Analysis Available',
    finding: 'Preliminary retrosynthesis identified 3 candidate routes with yield spread of 2.4× across options.',
    suggestion: 'Full route scoring (cost, yield, green metrics, scalability) requires deeper compound analysis.',
    impact: [
      { metric: 'Candidate routes', from: '—', to: '3',  delta: 'identified' },
      { metric: 'Yield spread',     from: '—', to: '2.4×', delta: 'between routes' },
      { metric: 'Confidence',       from: '—', to: 'Medium', delta: 'without deeper data' },
    ],
    cta: 'Engage Crucible chemistry team for full feasibility study.',
  },
  scenarios: [
    {
      name: 'Lowest Cost',     icon: '$', cost: '$— est.', costPerKg: 'scales with route',
      leadTime: '12–18 weeks', partnerCount: 4, highlight: 'Commodity-route estimate pending compound class confirmation',
      radar: { cost: 88, speed: 70, risk: 60, sustainability: 55, compliance: 82, scalability: 78 },
      partners: ['Nuada Specialty Chem', 'Meridian Intermediates', 'Basilisk Fine Chem', 'Continental Logistics'],
    },
    {
      name: 'Fastest',         icon: '⚡', cost: '$— est.', costPerKg: 'premium',
      leadTime: '8–10 weeks',  partnerCount: 3, highlight: 'Pre-qualified integrated facility with open capacity',
      radar: { cost: 64, speed: 92, risk: 68, sustainability: 50, compliance: 86, scalability: 80 },
      partners: ['Helix Organics (integrated)', 'Aurora QC Labs', 'Continental Logistics'],
    },
    {
      name: 'Fewest Partners', icon: '◈', cost: '$— est.', costPerKg: 'moderate',
      leadTime: '10–14 weeks', partnerCount: 2, highlight: 'Single-point-of-contact full-stack CDMO',
      radar: { cost: 72, speed: 80, risk: 66, sustainability: 56, compliance: 88, scalability: 82 },
      partners: ['Helix Organics (full-stack)', 'Continental Logistics'],
    },
    {
      name: 'Greenest',        icon: '◊', cost: '$— est.', costPerKg: 'slight premium',
      leadTime: '14–18 weeks', partnerCount: 4, highlight: 'Bio-catalysis and solvent-recovery options available',
      radar: { cost: 70, speed: 68, risk: 62, sustainability: 90, compliance: 88, scalability: 74 },
      partners: ['Mycelia BioCatalysis', 'Verdant Green Chem', 'Aurora QC Labs', 'Continental Logistics'],
    },
  ],
  map: {
    caption: 'Preliminary network — 14 partners screened against structural fingerprint',
    nodes: [
      { x: 20, y: 50, name: 'Nuada Specialty',  role: 'Synthesis',   active: true,  tier: 1 },
      { x: 38, y: 40, name: 'Meridian Inter.',  role: 'Intermediate',active: true,  tier: 1 },
      { x: 50, y: 60, name: 'Helix Organics',   role: 'Integrated',  active: true,  tier: 1 },
      { x: 62, y: 36, name: 'Basilisk Fine',    role: 'Purification',active: true,  tier: 1 },
      { x: 72, y: 58, name: 'Aurora QC',        role: 'QC',          active: true,  tier: 1 },
      { x: 84, y: 44, name: 'Continental Log.', role: 'Logistics',   active: true,  tier: 1 },
      { x: 15, y: 76, name: 'Mycelia BioCat',   role: 'Biocatalysis',active: true,  tier: 2 },
      { x: 40, y: 78, name: 'Verdant Green',    role: 'Green chem',  active: true,  tier: 2 },
      { x: 78, y: 78, name: 'Polaris Pharma',   role: 'Filtered',    active: false, tier: 3 },
    ],
  },
};

// Workflow stages — shown during the fake "AI is thinking" animation.
const WORKFLOW_STAGES = [
  { label: 'Parsing molecular structure',             detail: 'SMILES → canonical graph · stereochem check' },
  { label: 'Fingerprinting against capability graph', detail: 'Matching Morgan fingerprints to partner tooling' },
  { label: 'Screening regulatory surface',            detail: 'REACH · TSCA · ITAR · DEA · ICH · export controls' },
  { label: 'Computing manufacturability',             detail: 'Retrosynthesis · scale-up feasibility · yield modeling' },
  { label: 'Mapping raw-material sources',            detail: 'Feedstock availability · geographic risk · MOQ fit' },
  { label: 'Optimizing supply-chain scenarios',       detail: 'Cost · speed · risk · sustainability Pareto front' },
  { label: 'Scoring partner network',                 detail: 'Audit history · capacity · past performance' },
];
